/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package actions;

import java.io.File;
import java.io.FileWriter;
import java.util.Iterator;

import org.dom4j.Document;
import org.dom4j.Element;
import org.dom4j.io.OutputFormat;
import org.dom4j.io.SAXReader;
import org.dom4j.io.XMLWriter;

/**
 * <p>类名：deleteXML
 * <p>作用：删除节点
 * <p>@author :born to try
 */
public class deleteXML extends MySuperAction{
	private String[] title;
	private String[] describe;
	private String[] date; 
	private String[] url;
	private String[] id;
	private String[] deleteName;
	private String[] path;

	public String[] getTitle(){
		return title;
	}
	public void setTitle(String[] title){
		this.title=title;
	}
	public String[] getDescribe(){
		return describe;
	}
	public void setDescribe(String[] describe){
		this.describe=describe;
	}
	public String[] getDate(){
		return date;
	}
	public void setDate(String[] date){
		this.date=date;
	}
	public String[] getUrl(){
		return url;
	}
	public void setUrl(String[] url){
		this.url=url;
	}
	public String[] getId(){
		return id;
	}
	public void setId(String[] id){
		this.id=id;
	}
	public String[] getDeleteName(){
		return deleteName;
	}
	public void setDeleteName(String[] deleteName){
		this.deleteName=deleteName;
	}
	public String[] getPath(){
		return path;
	}
	public void setPath(String[] path){
		this.path=path;
	}
	public String execute()throws Exception{
		//获得要删除的资源的文件名
        String[] fileNames=deleteName;
        for(int i=0;i<fileNames.length;i++)
        System.out.println(fileNames[i]+ "大家好！！！！！！");
        //获得test.xml文件路径
        String path = getPath("webapps");
        String recordpath= path+"\\"+"test.xml";
		 //建立到test.xml的解析
        Document doc = null;
   	    Element root=null;
        SAXReader xmlReader = new SAXReader();
        doc = xmlReader.read(recordpath);
        root = doc.getRootElement(); 
        //创建新的 ElementIterator，沿 Element 树进行迭代；
        Iterator  it = root.elementIterator("resourceitem"); 
        Element elementNode=null;        
		//循环遍历 这个xml中的 记录，找到要删除的资源记录并把它删除
		while (it.hasNext()) { 					
			elementNode=  (Element) it.next(); 
			String url=elementNode.elementText("url");
			//如果这条记录的url中包含传递过来的fileName，说明这就是要删除的记录，把它删除，并跳出循环
			for(int i=0;i<fileNames.length;i++){
			    if(url.indexOf(fileNames[i])!=-1){
			    	root.remove(elementNode);
				    break;
			    }
			}
	    }
		//删除某些记录后，保存xml文件
		 try{  
			 OutputFormat format = OutputFormat.createPrettyPrint();
				//指定XML字符集编码 
				format.setEncoding("GBK");
				//创建xml流
			  XMLWriter writer = new XMLWriter(new FileWriter(new File(recordpath)),format);     
			  writer.write(doc);                               
			  writer.close();                                                       
		}catch(Exception ex){
			ex.printStackTrace(); 
		} 
			  //在放置资源的文件夹中把要删除的资源删除
		 for(int i=0;i<fileNames.length;i++){
			String filepath= path+"\\"+"resources"+"\\"+fileNames[i];
			//如果文件已经存在，则获得它的文件句柄
			File file=new File(filepath);							
			if(file.exists()&&file.isFile()){
				file.delete();	
			}
			
		}			    				  
		return "success";
					  
	}
	public String getPath(String Webapps){
		
		//在本地目录下新建一个文件存放结果用于测试 检索是否正确
		String   path   =  System.getProperty("catalina.home");	
		
		//因为不同的环境中user.dir指向的有的是tomcat根目录，有的是bin目录，
		 // 所以下面对 bin的位置进行判断，如果目录中含有bin则进行去掉bin目录的处理
		int binindex=path.indexOf("bin");
        if(binindex!=-1){
        	path=path.substring(0, binindex-1);
        }			
		path=path+"\\"+Webapps;
		return path;		    	
	}
}